# Generated by Django 4.1.3 on 2022-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemap",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
