# Generated by Django 4.1.3 on 2022-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0002_alter_sitemap_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("price", models.FloatField()),
                ("cover_url", models.URLField()),
            ],
        ),
    ]
