# Generated by Django 4.1.3 on 2022-12-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0004_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="source",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="robots.source",
            ),
            preserve_default=False,
        ),
    ]
