# Generated by Django 4.1.3 on 2022-11-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_news_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name="News",
            new_name="Article",
        ),
        migrations.RenameModel(
            old_name="NewsSource",
            new_name="ArticleSource",
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "media_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="topics.mediatype",
                    ),
                ),
            ],
        ),
    ]
