# Generated by Django 4.1.3 on 2022-11-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_article_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="topics.media"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="topics.topic"
            ),
        ),
    ]
