# Generated by Django 4.1.3 on 2022-11-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_alter_article_media_alter_article_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="cover_url",
        ),
    ]
