# Generated by Django 4.1.3 on 2022-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0006_remove_article_cover_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
