# Generated by Django 4.1.3 on 2022-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0007_alter_article_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="url",
        ),
        migrations.AddField(
            model_name="media",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
