# Generated by Django 4.1.3 on 2022-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0009_alter_media_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
